/* Axel settings, generated by configure */
#define _REENTRANT
#define _THREAD_SAFE
#define ETCDIR "/usr/local/etc"
#define LOCALE "/usr/local/share/locale"
#define ARCH "Darwin"

#define NOGETOPTLONG
#define DARWIN
